name: Python package

on:
  push:
    paths:
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
      - name: Lint with ruff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff ${{ steps.changed-files.outputs.all_changed_files }} --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff ${{ steps.changed-files.outputs.all_changed_files }} --format=github --target-version=py37 .
      - name: Test with pytest
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pytest ${{ steps.changed-files.outputs.all_changed_files }}
